#!/bin/bash
# intelligence-sync: opencode adapter
# Transforms source prompts to opencode's native resource model.
#
# Rules:
#   - Always-on (no `paths:`) -> SKIPPED here. opencode reads AGENTS.md
#     natively as its primary "Rules" surface (see opencode.ai/docs/rules).
#   - Path-scoped (with `paths:`) -> SKIPPED. opencode has no first-class
#     scoped-rule mechanism; users who want scoped rules can opt in via
#     `instructions:` globs in opencode.json. We do not synthesize that.
# Skills:
#   - Copied to .agents/skills/ (Agent Skills open standard; opencode
#     discovers `.agents/skills/<name>/SKILL.md` natively).
# Commands:
#   - For every synced skill, emit `.opencode/commands/<name>.md` so users can
#     invoke the skill as `/<name> [args]` directly from the slash menu —
#     replicating the Claude Code UX where every skill is also a slash
#     command. The command body delegates to the `skill` tool and forwards
#     `$ARGUMENTS` so any flags from the skill's `argument-hint` reach the
#     skill script unchanged. Cleanup is marker-based: only files containing
#     the generation marker are removed, so user-managed commands survive.
# Agents:
#   - Converted to .opencode/agents/<name>.md markdown agents
#     (mode: subagent) with frontmatter description/model/permission. The
#     body is the source agent's prompt, used directly as the system prompt.

source "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"

# Strip frontmatter, return body only.
# Direct call to the shared `strip_frontmatter` helper in lib/common.sh —
# duplicating the awk block here would violate the "all parsing in common.sh"
# convention (see CLAUDE.md / docs/CONVENTIONS.md).

sync_opencode_skills() {
    local repo_root="$1"
    local config_file="$2"
    local _output_dir="$3"

    # Skills -> .agents/skills/ (open standard; opencode reads it natively).
    # `sync_open_skill_dirs` owns clean + populate of this shared dir.
    local skills_dir="$repo_root/.agents/skills"
    sync_open_skill_dirs "$repo_root" "$config_file" "$skills_dir"
}

# Marker line embedded in every generated command file. Cleanup grep's for
# this exact string before deleting, so any user-authored command without it
# survives a sync.
OPENCODE_GEN_MARKER="<!-- Generated by intelligence-sync. Do not edit manually. -->"

# Generate one slash command per synced skill.
# For each `<src>/<skill>/SKILL.md`, write `.opencode/commands/<skill>.md`
# with `description:` copied from the skill's `description` (YAML-escaped) and a body that tells the
# current agent to load the skill via the `skill` tool and pass `$ARGUMENTS`.
# Files marked with $OPENCODE_GEN_MARKER are removed before regeneration; any
# user-managed command without the marker is preserved. A user file that
# shares a name with a skill is overwritten by design — that 1:1 name
# binding is the whole point of the wrap.
sync_opencode_commands() {
    local repo_root="$1"
    local config_file="$2"
    local output_dir="$3"

    local commands_dir="$output_dir/commands"
    mkdir -p "$commands_dir"

    # Marker-based cleanup: leave user-authored commands alone.
    local f
    if [ -d "$commands_dir" ]; then
        for f in "$commands_dir"/*.md; do
            [ -f "$f" ] || continue
            if grep -qF "$OPENCODE_GEN_MARKER" "$f" 2>/dev/null; then
                rm -f "$f"
            fi
        done
    fi

    local count=0
    while IFS= read -r src; do
        [ -z "$src" ] && continue
        local dir
        dir="$(resolve_source_dir "$repo_root" "$src")"
        [ -d "$dir" ] || continue
        for d in "$dir"/*/; do
            [ -d "$d" ] || continue
            local skill_name
            skill_name="$(basename "$d")"
            local skill_md="$d/SKILL.md"
            [ -f "$skill_md" ] || continue

            local description argument_hint
            description="$(get_frontmatter_value "description" "$skill_md")"
            argument_hint="$(get_frontmatter_value "argument-hint" "$skill_md")"

            local out_file="$commands_dir/$skill_name.md"
            {
                echo "---"
                echo "description: \"$(yaml_dq_escape "$description")\""
                echo "---"
                echo ""
                echo "$OPENCODE_GEN_MARKER"
                echo ""
                echo "Load and execute the \`$skill_name\` skill via the \`skill\` tool, then run it."
                echo ""
                if [ -n "$argument_hint" ]; then
                    echo "Pass these arguments to the skill: \$ARGUMENTS"
                    echo ""
                    echo "Argument hint from the source skill: \`$argument_hint\`"
                else
                    echo "Forward any provided arguments to the skill: \$ARGUMENTS"
                fi
            } > "$out_file"
            normalize_file_to_lf "$out_file"
            count=$((count + 1))
            echo "  command: /$skill_name"
        done
    done < <(read_yaml_list "$config_file" "skills")

    echo "  -> Commands: $count"
}

sync_opencode_agents() {
    local repo_root="$1"
    local config_file="$2"
    local output_dir="$3"

    local agents_dir="$output_dir/agents"
    mkdir -p "$agents_dir"

    local count=0
    while IFS= read -r src; do
        [ -z "$src" ] && continue
        local dir
        dir="$(resolve_source_dir "$repo_root" "$src")"
        [ -d "$dir" ] || continue
        for f in "$dir"/*.md; do
            [ -f "$f" ] || continue

            local name tier access description body
            name="$(basename "$f" .md)"
            tier="$(get_frontmatter_value "tier" "$f")"
            access="$(get_frontmatter_value "access" "$f")"
            description="$(get_frontmatter_value "description" "$f")"
            body="$(strip_frontmatter "$f")"

            local model edit_perm bash_perm
            model="$(get_model "$config_file" "opencode" "$tier")"

            # Map source `access:` to opencode permission keys.
            # `edit` gates write/edit/apply_patch; `bash` gates shell.
            case "$access" in
                readonly) edit_perm="deny";  bash_perm="deny"  ;;
                *)        edit_perm="allow"; bash_perm="allow" ;;
            esac

            local out_file="$agents_dir/$name.md"
            {
                echo "---"
                echo "description: \"$(yaml_dq_escape "$description")\""
                echo "mode: subagent"
                if [ -n "$model" ]; then
                    echo "model: \"$(yaml_dq_escape "$model")\""
                fi
                echo "permission:"
                echo "  edit: $edit_perm"
                echo "  bash: $bash_perm"
                echo "---"
                echo ""
                echo "<!-- Generated by intelligence-sync. Do not edit manually. -->"
                echo ""
                printf '%s\n' "$body"
            } > "$out_file"
            normalize_file_to_lf "$out_file"
            count=$((count + 1))
            echo "  agent: $name.md"
        done
    done < <(read_yaml_list "$config_file" "agents")

    echo "  -> Agents: $count"
}

sync_to_opencode() {
    local repo_root="$1"
    local config_file="$2"
    local output_dir="$3"

    echo "=== opencode ==="

    # Adapter owns .opencode/agents/ entirely (so removed/renamed source
    # agents don't linger). Other .opencode/* files (e.g. user-managed
    # opencode.json) are left untouched. .opencode/commands/ is owned
    # marker-by-marker — see sync_opencode_commands.
    rm -rf "$output_dir/agents"
    mkdir -p "$output_dir/agents"

    sync_opencode_skills "$repo_root" "$config_file" "$output_dir"
    sync_opencode_commands "$repo_root" "$config_file" "$output_dir"
    sync_opencode_agents "$repo_root" "$config_file" "$output_dir"

    echo "  -> Rules: skipped (AGENTS.md carries always-on; opencode has no native path-scoped rules)"
}
