#!/bin/bash
# intelligence-sync: Pi adapter
# Transforms source prompts to Pi's native resource model.
#
# Rules:
#   - Always-on (no `paths:`) -> SKIPPED here. Pi reads AGENTS.md natively.
#   - Path-scoped (with `paths:`) -> copied to .pi/intelligence-sync/rules/
#     and surfaced via a generated Pi extension that lists them in the system
#     prompt so the model can `read` the relevant rule on demand.
# Skills:
#   - Copied to .agents/skills/ (Agent Skills open standard, read by Pi)
# Agents:
#   - Converted to .pi/prompts/intelligence-agent-<name>.md prompt templates
#     so users can invoke a persona explicitly via `/intelligence-agent-<name>`.

source "$(dirname "${BASH_SOURCE[0]}")/../lib/common.sh"

pi_ts_escape() {
    local s="$1"
    s="${s//\\/\\\\}"
    s="${s//\"/\\\"}"
    s="${s//$'\r'/}"
    s="${s//$'\n'/ }"
    printf '%s' "$s"
}

pi_rule_paths() {
    local file="$1"
    awk '
        { sub(/\r$/, "") }
        NR == 1 && $0 != "---" { exit }
        NR == 1 { in_fm = 1; next }
        in_fm && $0 == "---" { exit }
        !in_fm { next }

        /^paths:[[:space:]]*$/ { in_paths = 1; next }
        in_paths && /^  - / {
            val = $0
            sub(/^  - /, "", val)
            gsub(/^["\047]|["\047]$/, "", val)
            print val
            next
        }
        in_paths && !/^  - / && !/^[[:space:]]*$/ { exit }
    ' "$file"
}

pi_agent_body() {
    # Thin alias around the shared helper in lib/common.sh; kept so older call
    # sites (and any future adapter logic) read symmetrically with sync_pi_*.
    strip_frontmatter "$1"
}

sync_pi_rules() {
    local repo_root="$1"
    local config_file="$2"
    local output_dir="$3"

    local rules_root="$output_dir/intelligence-sync/rules"
    local extension_file="$output_dir/extensions/intelligence-sync-rules.ts"
    local output_rel="${output_dir#$repo_root/}"
    local manifest=""
    local count=0

    mkdir -p "$rules_root" "$(dirname "$extension_file")"

    while IFS= read -r src; do
        [ -z "$src" ] && continue
        local dir
        dir="$(resolve_source_dir "$repo_root" "$src")"
        [ -d "$dir" ] || continue
        for f in "$dir"/*.md; do
            [ -f "$f" ] || continue
            local hp
            hp=$(has_paths "$f")
            [ "$hp" -eq 0 ] && continue

            local base rel_rule_path patterns_js display sep display_sep
            base="$(basename "$f")"
            rel_rule_path="$output_rel/intelligence-sync/rules/$base"
            patterns_js=""
            display=""
            sep=""
            display_sep=""

            cp "$f" "$rules_root/$base"
            normalize_file_to_lf "$rules_root/$base"

            while IFS= read -r pat; do
                [ -z "$pat" ] && continue
                local pat_escaped
                pat_escaped="$(pi_ts_escape "$pat")"
                patterns_js+="$sep\"$pat_escaped\""
                display+="$display_sep$pat"
                sep=", "
                display_sep=", "
            done < <(pi_rule_paths "$f")

            manifest+="    { path: \"$(pi_ts_escape "$rel_rule_path")\", patterns: [$patterns_js] },"$'\n'
            count=$((count + 1))
            echo "  rule: $base (scoped${display:+ — $display})"
        done
    done < <(read_yaml_list "$config_file" "rules")

    if [ "$count" -gt 0 ]; then
        {
            cat <<'EOF'
/**
 * Generated by intelligence-sync. Do not edit manually.
 * Lists path-scoped project rules generated from intelligence/rules/.
 */

import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

const scopedRules: Array<{ path: string; patterns: string[] }> = [
EOF
            printf '%s' "$manifest"
            cat <<'EOF'
];

export default function intelligenceSyncRulesExtension(pi: ExtensionAPI) {
    pi.on("before_agent_start", async (event) => {
        if (scopedRules.length === 0) {
            return;
        }

        const rulesList = scopedRules
            .map((rule) => `- ${rule.path} — paths: ${rule.patterns.join(", ")}`)
            .join("\n");

        return {
            systemPrompt:
                event.systemPrompt +
                `

## Scoped Project Rules

AGENTS.md already carries the always-on project rules. Additional path-scoped rules are available on demand:

${rulesList}

When the task touches files that match one of these path patterns, use the read tool to load the relevant rule file before making changes.`,
        };
    });
}
EOF
        } > "$extension_file"
        normalize_file_to_lf "$extension_file"
    fi

    echo "  -> Rules: $count scoped"
}

sync_pi_skills() {
    local repo_root="$1"
    local config_file="$2"
    local _output_dir="$3"

    # Skills -> .agents/skills/ (open standard; Pi reads it natively).
    # `sync_open_skill_dirs` owns clean + populate of this shared dir.
    local skills_dir="$repo_root/.agents/skills"
    sync_open_skill_dirs "$repo_root" "$config_file" "$skills_dir"
}

sync_pi_agents() {
    local repo_root="$1"
    local config_file="$2"
    local output_dir="$3"

    local prompts_dir="$output_dir/prompts"
    local count=0

    mkdir -p "$prompts_dir"

    while IFS= read -r src; do
        [ -z "$src" ] && continue
        local dir
        dir="$(resolve_source_dir "$repo_root" "$src")"
        [ -d "$dir" ] || continue
        for f in "$dir"/*.md; do
            [ -f "$f" ] || continue

            local name rel desc access template_desc body prompt_file access_note
            name="$(basename "$f" .md)"
            rel="${f#$repo_root/}"
            desc="$(get_frontmatter_value "description" "$f")"
            access="$(get_frontmatter_value "access" "$f")"
            body="$(pi_agent_body "$f")"
            prompt_file="$prompts_dir/intelligence-agent-$name.md"

            template_desc="Use $name persona"
            [ -n "$desc" ] && template_desc="$template_desc — $desc"

            access_note=""
            if [ "$access" = "readonly" ]; then
                access_note=$(cat <<'EOF'
## Access Mode

Default to read-only analysis. Do not change files or run mutating commands unless the user explicitly asks you to override this agent's normal restriction.

EOF
)
            fi

            {
                echo "---"
                echo "description: \"$(yaml_dq_escape "$template_desc")\""
                echo "argument-hint: \"[task]\""
                echo "---"
                echo ""
                echo "<!-- Generated by intelligence-sync. Do not edit manually. -->"
                echo ""
                printf 'Adopt the `%s` agent persona for this task.\n' "$name"
                echo ""
                printf 'Source: `%s`\n' "$rel"
                if [ -n "$desc" ]; then
                    echo "Use this persona when: $desc"
                    echo ""
                fi
                if [ -n "$access_note" ]; then
                    printf '%s\n' "$access_note"
                fi
                echo "## Agent Instructions"
                echo ""
                printf '%s\n' "$body"
                echo ""
                echo "User task: \$@"
            } > "$prompt_file"
            normalize_file_to_lf "$prompt_file"
            count=$((count + 1))
            echo "  agent: intelligence-agent-$name.md"
        done
    done < <(read_yaml_list "$config_file" "agents")

    echo "  -> Agents: $count prompt template(s)"
}

sync_to_pi() {
    local repo_root="$1"
    local config_file="$2"
    local output_dir="$3"

    echo "=== Pi ==="

    local prompts_dir="$output_dir/prompts"
    local extensions_dir="$output_dir/extensions"

    rm -rf "$output_dir/intelligence-sync"
    mkdir -p "$prompts_dir" "$extensions_dir"
    find "$prompts_dir" -mindepth 1 -maxdepth 1 -type f -name 'intelligence-agent-*.md' -delete 2>/dev/null || true
    rm -f "$extensions_dir/intelligence-sync-rules.ts"

    sync_pi_rules "$repo_root" "$config_file" "$output_dir"
    sync_pi_skills "$repo_root" "$config_file" "$output_dir"
    sync_pi_agents "$repo_root" "$config_file" "$output_dir"
}
